server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    metadataMap:
      instanceId: ${random.value}

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id-1:${spring.application.name}-2:${spring.application.instance_id-3:${server.port}}}    
